#!/bin/bash

# loads PHP composer bins
if [ -d "$HOME/.composer/bin" ] ; then
  PATH="$HOME/.composer/bin:$PATH"
fi

# WP-CLI directory
PATH=$HOME/.wp-cli/bin:$PATH

# some more ls aliases; or exa (if installed)
which exa >/dev/null 2>/dev/null
if [ $? = 1 ]; then
  alias ll='ls -alF'
  alias la='ls -A'
  alias l='ls'
else
  alias ll='exa -l --git'
  alias la='exa -a'
  alias lf='exa -bgHliS'
  alias l='ll'
fi

#sudo preserves path
#alias sudo="sudo env PATH=$PATH"

#cl : cd with a ls
function cl () {
  cd $1 && l
}

# OSX-specific
if [ `uname` = 'Darwin' ]; then
  alias wget="curl -O"
fi

# Windows-specific
if [ `uname -o` = 'Cygwin' ]; then
	alias c:="cd /cygdrive/c"
	alias d:="cd /cygdrive/d"
  alias e:="cd /cygdrive/e"
  alias x:="cd /cygdrive/x"
  alias z:="cd /cygdrive/z"

  # for windows ruby support
  export homeFolder="C:/Users/memuller"
fi

# Linux-specific
if [ `uname -o` = 'GNU/Linux' ]; then
  # pipes sound line input to output w/ gstreamer/pulse
  alias listen='gst-launch-1.0 pulsesrc ! pulsesink'
  # gets distro name
  alias distro="lsb_release -i | sed 's/Distributor ID://' | sed 's/[[:space:]]//g'"
  # loads audio loopback pulseaudio module
  pactl load-module module-loopback
fi

# some useful commands
source ~/Repos/env/dotfiles/lib/unix_utils.sh

# Windows WSL-specific
if [ `uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/p'` ]; then
  export WSL=1

  # when a command is not found, tries to find an executable with the same name and run it
  command_not_found_handle() {
    if cmd.exe /c "(where $1 || (help $1 |findstr /V Try)) >nul 2>nul && ($* || exit 0)"; then
        return $?
    else
        if [ -x /usr/lib/command-not-found ]; then
           /usr/lib/command-not-found -- "$1"
           return $?
        elif [ -x /usr/share/command-not-found/command-not-found ]; then
           /usr/share/command-not-found/command-not-found -- "$1"
           return $?
        else
           printf "%s: command not found\n" "$1" >&2
           return 127
        fi
    fi
  }

  # does the same, but for ZSH
  command_not_found_handler() {
    command_not_found_handle "$@"
    return $?
  }
fi


if [ -d "$HOME/Repos/ruby/danbooru-ruby-grabber" ]; then
  source ~/Repos/ruby/danbooru-ruby-grabber/aliases
fi

if [ -d "$HOME/Repos/env/vubuntu" ]; then
  source ~/Repos/env/vubuntu/vubuntu.sh
fi

# ruby is fun
alias be='bundle exec'

# git
alias g='git'

#python
alias py='python'
alias py2='python2'
alias py3='python3'

# docker
alias dc='docker-compose'
if [ "$WSL" = "1" ]; then
  export COMPOSE_CONVERT_WINDOWS_PATHS=1
fi