#!/bin/bash

# loads PHP composer bins
if [ -d "$HOME/.composer/bin" ] ; then
  PATH="$HOME/.composer/bin:$PATH"
fi

# WP-CLI directory
PATH=$HOME/.wp-cli/bin:$PATH

# some more ls aliases; or exa (if installed)
which exa >/dev/null 2>/dev/null
if [ $? = 1 ]; then
  alias ll='ls -alF'
  alias la='ls -A'
  alias l='ls'
else
  alias ll='exa -l --git'
  alias la='exa -a'
  alias lf='exa -bgHliS'
  alias l='ll'
fi

#sudo preserves path
#alias sudo="sudo env PATH=$PATH"

#cl : cd with a ls
function cl () {
  cd $1 && l
}

# OSX-specific
if [ `uname` = 'Darwin' ]; then
  alias wget="curl -O"
fi

# Windows-specific
if [ `uname -o` = 'Cygwin' ]; then
	alias c:="cd /cygdrive/c"
	alias d:="cd /cygdrive/d"
  alias e:="cd /cygdrive/e"
  alias x:="cd /cygdrive/x"
  alias z:="cd /cygdrive/z"

  # for windows ruby support
  export homeFolder="C:/Users/memuller"
fi

# Linux-specific
if [ `uname -o` = 'GNU/Linux' ]; then
  # pipes sound line input to output w/ gstreamer/pulse
  alias listen='gst-launch-1.0 pulsesrc ! pulsesink'
  # gets distro name
  alias distro="lsb_release -i | sed 's/Distributor ID://' | sed 's/[[:space:]]//g'"
fi

# some useful commands
source ~/Repos/env/dotfiles/lib/unix_utils.sh

if [ -d "$HOME/Repos/ruby/danbooru-ruby-grabber" ]; then
  source ~/Repos/ruby/danbooru-ruby-grabber/aliases
fi

# ruby is fun
alias be='bundle exec'

# git
alias g='git'

#python
alias py='python'
alias py2='python2'
alias py3='python3'
