#!/bin/bash

# loads PHP composer bins
if [ -d "$HOME/.composer/bin" ] ; then
  PATH="$HOME/.composer/bin:$PATH"
fi

# adds local sbin/bin directories, if there're there
if [ -d "/usr/local/bin" ] ; then
  PATH="/usr/local/bin:/usr/local/sbin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ] ; then
    PATH="$HOME/.bin:$PATH"
fi

# adds Android SDK to path, if it's there
if [ -d "$HOME/.android" ] ; then
    PATH="$HOME/.android/tools:$PATH"
fi

# adds git prompt/completion stuff from home
if [ -f "$HOME/.bin/git-prompt.sh" ]; then
  source ~/.bin/git-completion.bash
  source ~/.bin/git-prompt.sh
fi

# WP-CLI directory
PATH=$HOME/.wp-cli/bin:$PATH

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#sudo preserves path
#alias sudo="sudo env PATH=$PATH"

#cl : cd with a ls
function cl () {
  cd $1 && ls
}

# OSX-specific
if [ `uname` = 'Darwin' ]; then
  alias wget="curl -O"
fi

# Windows-specific
if [ `uname -o` = 'Cygwin' ]; then
	alias cdc="cd /cygdrive/c"
	alias cdd="cd /cygdrive/d"
  alias cde="cd /cygdrive/e"

  # for windows ruby support
  export homeFolder="C:/Users/memuller"
fi

# Linux-specific
if [ `uname -o` = 'GNU/Linux' ]; then
  # pipes sound line input to output w/ gstreamer/pulse
  alias listen='gst-launch-1.0 pulsesrc ! pulsesink'
  # gets distro name
  alias distro="lsb_release -i | sed 's/Distributor ID://' | sed 's/[[:space:]]//g'"
fi

# some useful commands
source ~/Repos/dotfiles/lib/unix_utils.sh

if [ -d "$HOME/Repos/danbooru-ruby-grabber" ]; then
  source ~/Repos/danbooru-ruby-grabber/aliases
fi

# ruby is fun
alias be='bundle exec'

# git
alias g='git'

# composer
alias composer="php $HOME/.composer/composer.phar"
