version: '3.5'
services:
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  
  admininastror:
    image: adminer
    ports:
      - "3001:8080"
    restart: always
    environment:
      ADMINER_DESIGN: pepa-linha
      VIRTUAL_HOST: 'sql.test'
    networks:
      - databases

    external_links:
      - memuller_wp_db_1:memuller
      - wpmudev_db_1:wpmudev
      - openproject_dev_db_1:openproject

networks:
  default:
    name: nginx_proxy
  databases:
    name: databases
    