include .env

build:
	docker-compose down --remove-orphans ;
	docker-compose rm ;
	docker-compose build ;

run:
	docker-compose up ;

start:
	docker-compose up --detach ;

stop:
	docker-compose stop ;
down:
	docker-compose down;
